Feature/constraint operators
wingtra/unleash-client-cpp pull request #9
Opened 2024-02-15 16:48 UTC by bolomcs50

2024-02-16 08:13 UTC, bolomcs50 commented
/retest

2024-02-19 07:37 UTC, bolomcs50 commented
/retest

2024-02-26 13:41 UTC, bernedom requested changes

2024-02-26 13:41 UTC, bernedom commented on include/unleash/strategies/strategy.h
> +    bool inverted;
initialize these with a sane default value
```
bool inverted{false};
bool caseInsensitive{false};
```

2024-02-27 08:38 UTC, bolomcs50 commented
@bernedom The thing with CI here is Windows passes, Ubuntu tests pass but the check fails because of some later coverage upload step fails and MacOS does not bass because during the tests it somehow can't parse a .json
We reproduced the failure to run tests on a Mac. The library itself compiles and works, though.
Do we merge anyways?

2024-03-04 15:14 UTC, bernedom approved these changes

2024-03-21 13:22 UTC, merged